### ISSUE TITLE
How do i remove Ads?

### ISSUE THREAD

**Issue by tejaspanchall** [Manj0tBenipal/kaido#1]
i do want to set any ads on my localhost test, can you tell me how do i remove ads as i am not finding anything for it.

**Comment by Manj0tBenipal** [comment]
Since I am using third party servers, the control over ads is on them. You
can set the state of ad lock enabled to true for now. It's gonna render
some of the servers useless but stream wish and filelions will continue to
work.

**Comment by tejaspanchall** [comment]
if you can tell me the ads service name that you're using, then it would be much help.

Anyways I don't see any services other then consumet, kitsu, jikan.

So still can't understand and how ads are coming!!

**Comment by Manj0tBenipal** [comment]
Let me put it into simple words, You can open WatchAnime,jsx in the pages folder under src directory. You can see that there is an iframe element having the episode server's URL as its src attribute. That is a third-party service that is not owned by me. I am using it for fetching episodes because I cannot directly access an episode's video file due to CORS policies and hence cannot implement a custom video player. So I have to rely on these servers and the ads are generated by those servers, not me. You can notice that ads only pop up in the video frame, not on the website itself and you will face redirects only when you click on the iframe element containing video.

**Comment by tejaspanchall** [comment]
Okay got it, so is there any way to block default ads? I tried the iframe sandbox attribute but it's not working.

**Comment by Manj0tBenipal** [comment]
The servers will break except the two I mentioned. I have already done that
by conditionally rendering iframe based on the state adBlockIsOn. So that's
the only way to do it.

**Comment by tejaspanchall** [comment]
can you tell me from which API videos are coming? I have something in my mind to try.

**Comment by Manj0tBenipal** [comment]
I'm using consumet.ts I'm using the node.js library. There is also a
restfulApi of consumet that you can try.

**Comment by tejaspanchall** [comment]
I'm confused, I mean videos are coming from Consumet then why ads are showing, as Consumet doesn't have ads in their resources. lemme contact consumet only.

**Comment by Manj0tBenipal** [comment]
Look, The API is only responsible for providing you with server URLs. API has no control over how you integrate the server into your app or how the server behaves while being in your app. That's the best example I can give you.

**Comment by Manj0tBenipal** [comment]
You should read the API documentation try the API and integrate it in your App or fork this repo and understand how it works. and what data it is giving
